language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: hmanager
  token:
    secure: M1w1QUOzD8bUdvrfwocD+VVBT+MC85Ys2xgXdSxEE+kR2pR0wOWU8+i0aGeVGDl/08oGw6oq39I32vVA/IzHQM6AwrTqHH5dsm/7xu4GNfP+hudqGlReU7XrRUN+OD7pLXyimlFVkLKKXfMgtPaevFyhHsrpBgVVkvhdDZ4yYnQyOhkeWa3dr3bu9v3WtG+uUeLqll8Bn9+GtUe/Uugk0YYf31MzjMnipwKDeeMQ4urslztYSRGeu/pIJ/jz+cZeyVXHtkN7gqeBBcB3k82AJoNZplfvuUbYTvuZ2+9Lvhuni+gib60BGXEIAJWQGqxazLXqhgxFcy9L8UmPoewN2kFyM1tP25RP9wole5orONBkhdSeUkOzhTsLz5Kp0jbGm2hP6yjyuxCCAOVs7rzTu3drxtdGZREanKpQb0FLtUgjnILaBAbn6xfwjF1FMoBiHV9ROAI0eKwtQRGB1Qrj2BVunaFAwdOYuUwIpoq8xW3py6GulVdPWmWkoIzn7T/hLhXd4JlQMcyb0jQ/dZfntDVB+UBL66ukarV2W7w4mO61TZy1o83UrMJV5tYaK7Ggf7F8DB59Iy3yd49wryaDVPzsGXMLBoeBOuh+8M81PKIdKyLXYk5DzbU7XphoiByUD+YrXessPbgNVe8hN4OXJRKefVHsDqn7tKYZxidAU+k=
  branches:
  - register_module
script:
- sonar-scanner
env:
  global:
    secure: fZWxQwxI49xncfT7gJqS0ZDBWpeOurzmoRvKc6lyRfD609bxzWmAEXjq2oDI/BCDzR43W5BQG28VhsZ1fCmbuOgA5Ka+YTINuVbz1MeL3bRJHj619AlHl1CKULHSrZynVft+VEdBTUTQBaPmSKd9JPTQSv31IvKy0XVxIcHiGFrDyhkYIEE3p47OYcuSCnevdpD8cs8y/fzukEJmydenyxb35l7TTodxw38fLD1EFHVgjG13V/XBW2UdZBBQFgnGsmNPK4Yr3etmiq012VQYTkDuPy8+ghObKHZqzY9ZHChUkMT06xfKWEw8c9QasWTyHEx+Cup7vnAAvqtU8VcA3DWlIfpsn9g+XOGrMyZtYcFEMsZuZC3+JhwFLXFszWB0Y+uoBRuR3PwXFIs83k7YU9NVfD32AGJViuIiU5dR0QPCpdjuk/C/V3dQZV8z4g+xde639/FpLuXzVZsbabw4NWfQzIFOWMlDhh++rGNbIE+/i3PdV6BcV6MvP7rkKYsnmZ1SiGrlXoICLRdLmsfZA+JaLXQCKfC3tIPz9NDsE6C6GZ0pvHiRBdW3u2bZeKPwbMHurdVBKol8G9+iGre6IqTRBEYW7w6eGo/+ErQOimQMMKrp1XASS8SwBc8UF2crsG5Fpz49Mwed8vNaRpfhMjrXogICYjCxWP/Jbyzr3q8=
